CREATE SCHEMA sa;

CREATE TABLE sa.T_USR_MASTER
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) ,
username varchar(255) NOT NULL,
password varchar(255),
accountCreatedDate TIMESTAMP  NOT NULL ,
isActive varchar(255),
PRIMARY KEY (id)
);

CREATE TABLE sa.T_REM_MASTER(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
userid INTEGER NOT NULL,
rem_name varchar(255) NOT NULL,
rem_create_date varchar(255)NOT NULL ,
rem_alarm  TIMESTAMP NOT NULL ,
PRIMARY KEY (id)
);


ALTER TABLE sa.T_REM_MASTER ADD CONSTRAINT rem_usr_fk Foreign Key (userid) REFERENCES sa.T_USR_MASTER(id);
INSERT INTO sa.T_USR_MASTER (username,password,isActive) VALUES ('VAIBHAV','PRAJAPATI','ACTIVE');
INSERT INTO sa.T_REM_MASTER(userid,rem_name,rem_alarm) VALUES (1,'VAIBHAV BIRTHDAY','1991-01-25 00:00:00.000')