spring.mvc.view.prefix: /WEB-INF/view/
spring.mvc.view.suffix: .jsp
server.context-path: /springBootExample
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.database-platform: org.hibernate.dialect.DerbyDialect